<a href="https://colab.research.google.com/github/DiegoAristizabal15/Python-DataScientist/blob/main/Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![portada-24.png]()




<h1> Iniciación en Python</h1>


Python es un lenguaje de programación interpretado cuya filosofía hace hincapié en la legibilidad de su código. ​ Se trata de un lenguaje de programación multiparadigma, ya que soporta parcialmente la orientación a objetos, programación imperativa y, en menor medida, programación funcional. Es un lenguaje interpretado, dinámico y multiplataforma.

Es administrado por la Python Software Foundation. Posee una licencia de código abierto, denominada Python Software Foundation

<p><a name="contents"></a></p>

# Contenido Sesión 1

- <a href="#colabIntro">1. Introducción al Colaboratory de Google</a><br>
- <a href="#pythonIntro">2. Introducción a Python</a><br>

<p><a name="colabIntro"></a></p>

# 1) Introducción a Google Colaboratory

[[Contenidos]](#contents)

Este documento que está leyendo es un [Notebook de Jupyter](https://jupyter.org/), almacenado en el Colaboratory de Google. No es una página estática, se trata de un ambiente interactivo en el cual puede ejecutar scrips en Python, además de otros programas.

Por ejemplo, a continuación se muestra una **celda de código** con un pequeño script de Python que calcula un value, lo almacena en una variable y lo imprime en pantalla:

In [ ]:
# A continuación se realiza un cálculo sencillo del número de segundos en un año, se almacena dicho cálculo en la variable secs_per_year y se imprime en pantalla

secs_per_year=365*24*3600

print(secs_per_year)

31536000

Para ejecutar el anterior código, se debe seleccionar haciendo click en la celda, y se debe hacer click el botón "play" a la izquierda de la celda; también puede usar los atajos de teclado "Shift/Ctrl+Enter".

Todas las variables son almacenadas de forma global, de tal manera que se puede usar y modificar en celdas diferentes. En los dos siguientes ejemplos se muestran modificaciones ejecutadas sobre la variable secs_per_year

In [ ]:
print("Valor de la variable inicial",secs_per_year)

#Modificación 1 de la variable sec_per_year

secs_per_year=secs_per_year/2

print("Valor de la variable modificado", secs_per_year)

Valor de la variable inicial 15768000.0
Valor de la variable modificado 7884000.0

## More Resources

Learn how to make the most of Python, Jupyter, Colaboratory, and related tools with these resources:

### Working with Notebooks in Colaboratory
- [Overview of Colaboratory](/notebooks/basic_features_overview.ipynb)
- [Guide to Markdown](/notebooks/markdown_guide.ipynb)
- [Importing libraries and installing dependencies](/notebooks/snippets/importing_libraries.ipynb)
- [Saving and loading notebooks in GitHub](https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb)
- [Interactive forms](/notebooks/forms.ipynb)
- [Interactive widgets](/notebooks/widgets.ipynb)

<p><a name="pythonIntro"></a></p>

# 2) Introducción a Python

[[Contenidos]](#contents)

El objetivo de la presente sección es el de suministrar al lector una breve introducción al lenguaje Python, y ayudar a los principiantes a familiarizarse con dicho lenguaje.

<p><a name="sections"></a></p>

#Secciones

- <a href="#mods">2.1. Módulos</a><br>
- <a href="#ayuda">2.2. Ayudas y descripciones</a><br>
- <a href="#vars">2.3. Variables y tipos</a><br>
 - <a href="#syms">2.3.1. Nombres de variables</a><br>
  - <a href="#asign">2.3.2. Asignación</a><br>
  - <a href="#ftypes">2.3.3. Tipos fundamentales</a><br>
- <a href="#ops&comps">2.4. Operadores y comparaciones</a><br>
  - <a href="#exercise-1">2.4.1. Ejercicios y problemas</
  - <a href="#booleans">2.5. Booleanos</a><br>
 - <a href="#mscut">2.5.1. Atajos de operaciones matemáticas y asignaciones</a><br> 
 - <a href="#exercise0">2.5.2. Ejercicios y problemas</a><br>
- <a href="#sltd">2.5.3 Strings, Listas y diccionarios</a><br>
  - <a href="#strings">2.5.4. Strings</a><br>
  - <a href="#alist">2.5.5. List</a><br>
  - <a href="#tuples">2.5.6. Tuplas</a><br>
  - <a href="#diccionarios">2.5.7. Diccionarios</a><br>
  - <a href="#exercise1">2.5.8. Ejercicios y problemas</a><br>
- <a href="#indent">2.6. Intentación</a><br>
- <a href="#controlFlow">2.7. Control Flow</a><br>
 - <a href="#cond">2.7.1. Sentencias condicionales: if, elif, else </a><br>
 - <a href="#exercise2">2.7.2. Ejercicios y problemas</a><br>
- <a href="#iter">2.8. Ciclos lógicos </a><br>
 - <a href="#cicl">2.8.1 Ciclos for y while </a><br>
 - <a href="#contr">2.8.2 Sentencias de control de bucles</a><br>
 - <a href="#ftypes">2.8.3. Ejercicios y problemas</a><br>
- <a href="#func">2.9. Funciones y clases </a><br>
 - <a href="#funci">2.9.1. Funciones</a><br>
 - <a href="#class">2.9.2. Clases </a><br>
 - <a href="#exercise4">2.4.2. Ejercicios y problemas</a><br>

<p><a name="mods"></a></p>

##2.1. Módulos

[[Secciones]](#sections)

La mayoria de funcionalidades en Python estan proporcionadas por los módulos. Para poder usar un módulo en un programa de Python lo primero que se debe realizar es importarlo mediante la sentencia **import**. Por ejemplo, para importa el módulo *math*, el cual contiene gran variedad de funciones matemáticas, podemos hacer lo siguiente

In [ ]:
import math

La línea de código anterior implica la importación de todo el módulo, haciéndolo disponible para su uso posterior dentro del programa. Por ejemplo, podemos usar funciones triconométricas para calcular algún valor y almacenarlo en una variable:

In [ ]:
x = math.cos(2*math.pi)
x

1.0

En lugar de importar una librería completa, lo que puede llevar a un tiempo de ejecución o un consumo de memoria innecesario, podemos escoger importar unas cuantas funciones del módulo haciendo explicito cuales de ellas queremos importar. Por ejemplo, podemos elegir importar solo las funciones $cos$ y el valor de $\pi$:

In [ ]:
from math import cos, pi

x = cos(2*pi)
x

1.0

También es posible asignarle un nombre de acceso a los modolus o símbolos que se importan mediante el uso de **as**:

In [ ]:
import numpy as np
from math import pi as number_pi

#A continuación, convertímos el número pi de radianes a grados.

x = np.rad2deg(number_pi)
x

180.0

<p><a name="ayuda"></a></p>

## 2.2. Ayudas y descripciones

[[Secciones]](#sections)

Mediante el uso de la función $help$, se puede obtener una descripción de casi todas las funciones. Por ejemplo, para obtener una descripción de la funcion $log$ de la libreria $math$ ejecutamos el siguiente comando:

In [ ]:
help(math.log)

Help on built-in function log in module math:

log(...)
    log(x, [base=math.e])
    Return the logarithm of x to the given base.

    If the base not specified, returns the natural logarithm (base e) of x.

Tambien puede obtener la ayuda poniendo el sígno interrogante (?) al final de la expresión, así:

In [ ]:
math.log?

In [ ]:
math.log(10)

2.302585092994046

In [ ]:
math.log(10,2)

3.3219280948873626

In [ ]:
math.log(10,10)

1.0

<p><a name="vars"></a></p>

## 2.3. Variables y tipos

[[Secciones]](#sections)

<p><a name="syms"></a></p>

### 2.3.1. Variables y tipos

Los nombres de las variables en Python pueden contener caracteres alfanuméricos *a-z*, *A-Z*, *0-9* y algunos caracteres especiales como _. Los nombres de las variables deben comenzar con una letra. 

Por convención, los nombres de las variables comienzan con letras minúsculas, y los nombres de las Clases con letras mayúsculas.

Adicionalmente, existe un número de palabras claves que no pueden ser usadas como nombres de variables. Estas palabras claves son:

> `and, as, assert, break, class, continue, def, del, elif, else, except, exec, finally, for, from, global, if, import, in, is, lambda, not, or, pass, print, raise, return, try, while, with, yield`

<p><a name="asign"></a></p>

### 2.3.2. Asignación.

En Python, el operado de asignación es "=".  Python es un lenguaje de tipado dinámico, de tal forma que no es necesario asignarle un tipo a la variable cuando es creada.

La asignación de un valor a una variable crea la variable. Por ejemplo:

In [ ]:
# asignación a una variable

x = 1.0

Aunque no se hizo explicito, la variable tiene un tipo asociado a ella. El tipo de la variable puede deducirse del valor que le fue asignado. También podemos consultar el tipo mediante la función `type`:

In [ ]:
type(x)

float

Si asignamos a la variable un nuevo valor, su tipo puede cambiar:

In [ ]:
x = 1
type(x)

int

In [ ]:
x='hola'
type(x)

str

Si intentamos usar una variable que no ha sido definida aun, obtenemos un error `NameError` (Nótese que usarémos en los notebooks los bloques `try/except` para tratar las excepciones, de tal forma que el notebook no se interrumpa). 

En el siguiente código, intentaremos usar la función `print` de tal forma que si ocurre la excepción `NameError`, se imprime un mensaje en pantalla; de lo contrario, se generará un error. Más adelante, en el presente notebook, se estudiará mas detalladamente el manejo de excepciones.

In [ ]:
try:
    print(y)
except(NameError) as err:
    print("NameError", err)
else:
    raise

NameError name 'y' is not defined

<p><a name="ftypes"></a></p>

### 2.3.3. Tipos fundamentales.

En Python, los tipos fundamentales son 





1.   Enteros (int).
2.   Punto flotante (float).
3.   Buleanos (boolean)
4.   Cadena de caracteres (strings).

Veamos algunos ejemplos de estos tipos:

In [ ]:
# integers

x = 1
type(x)

int

In [ ]:
# float 

x = 1.0
type(x)

float

In [ ]:
# boolean

b1 = True
b2 = False

type(b1), type(b2)

(bool, bool)

In [ ]:
# string
s = "Hola Mundo"
s = 'Hola Mundo'
type(s)

str

<p><a name="ops&comps"></a></p>

## 2.4. Operadores y comparaciones.

[[Secciones]](#sections)

La mayoria de operadores y comparaciones poseen el significado al que, comunmente, estamos acostumbrados.
<br>
<br>
*   Operadores aritméticos  `+`, `-`, `*`, `/`, `**` (potencia), `%` (módulo)

In [ ]:
1 + 2, 1 - 2, 1 * 2, 5/3, 5//3, 5 % 3

(3, -1, 2, 1.6666666666666667, 1, 2)

En Python 2.7, el tipo de división (/) que se ejecute, depende del tipo de números involucrados. Si todos los números son enteros, la división será una divión entera, de lo contrario, será una operación en coma flotante. En Python 3, este hecho ha cambiado y las fracciones no se pierden cuando se dividen dos enteros (para las divisiones enteras se puede usar el operdor //)

In [ ]:
# En Python 3 las siguientes dos operaciones daran el mismo resultado.
# En Python 2, la primera de ellas será tratada como una división entera.

print(1/2)
print(1/2.0)
print(11//6.0)

0.5
0.5
1.0

In [ ]:
# Nótese que la potenciación en Python se escribe de la forma ** y
# no como ^

2**3

8


*   Los buleanos están conectados o precedidos por palabras como `and`, `not`, `or`.

In [ ]:
True and False

False

In [ ]:
not False

True

In [ ]:
not True

False

In [ ]:
True or False

True

<p><a name="exercise-1"></a></p>

## 2.4.1 Ejercicios y problemas

## Problemas y ejercicios

*  **Ejercicio 1**

Dado un número entero (dias), determine y muestre el equivalente en años, meses y días sobrantes. Por simplicidad suponga que un año tiene 365 días y que cada mes tiene 30 días. Use los operadores // y % para obtener cociente y resíduo.

Ejemplo. 1372 días equivalen a 3 años, 9 meses y 7 días.

In [ ]:
n=int(input("Digite el valor en Días:  "))
Anios = n / 365
r = n % 365
Meses = r / 365
Dias = r % 30
print("Años = ",Anios)
print("Meses = ",Meses)
print("Días = ",Dias)

Digite el valor en Días:  1372
Años =  3.758904109589041
Meses =  0.7589041095890411
Días =  7

* **Ejercicio 2**

Dado un número entero de cuatro cifras. Muestre el mismo número pero con las cifras en orden opuesto.

In [ ]:
A = int(input("Ingrese un numero de cuatro cifras: "))

# para obtener la ultima cifra utilizamos el %

C4 = A % 10
C3 = int((A % 100)/10)
C2 = int((A % 1000)/100)
C1 = int(A-(A % 1000))/1000

#Realizamos la concatenacion 
print(str(C4)+str(C3)+str(C2)+str(C1))

Ingrese un numero de cuatro cifras: 4538
8354.0

<p><a name="booleans"></a></p>

### 2.5 Booleanos



*   Operadores de comparación `>`, `<`, `>=`(mayor o igual), `<=` (menor o igual), `==` (igual), `!=`(no igual) y `is` (identico).

In [ ]:
2>1,2<1

(True, False)

In [ ]:
2>3,2<2

(False, False)

In [ ]:
4<=4,4>=4

(True, True)

In [ ]:
#igual a
[3,2]==[3,2]

True

In [ ]:
# Not equal to

2 != 5

True

*   Operador buleano

In [ ]:
x = True
y = False

print(not x)
print(x and y)
print(x or y)

False
False
True

*   Comparación de strings

In [ ]:
"estar bien" in "Me gusta estar bien"

True

In [ ]:
"estan" not in "Me gusta estar bien"

True

<p><a name="mscut"></a></p>

### 2.5.1 Atajos de operaciones matemáticas y asignaciones.

[[Secciones]](#sections)

Por ejemplo, la siguiente asignación y operación:

In [ ]:
a = 2
a = a*2
print(a)

4

el comando `a = a * 2`, puede ser abreviado como `a *= 2`. Este tipo de abreviaciones funcionan con las siguientes operaciones `+=`, `-=`, y `/=`.

In [ ]:
a = 4
a *= 4
print(a)

16

In [ ]:
b=3
b/=2
b

1.5

<p><a name="exercise0"></a></p>

### 2.5.2. Ejercicios y problemas




*   **Uso con if**

Los condicionales if evalúan una condición que es un valor bool.

In [ ]:
a = 1
b = 2
if b > a:
    print("b es mayor que a")

b es mayor que a

La expresión que va después del if es siempre evaluada hasta que se da con un booleano.

In [ ]:
if True:
    print("Es True")

Es True

Realiza un programa que lea 2 números por teclado y determine los siguientes aspectos. (es suficiene con mostrar True o False)

Si los dos números son iguales

In [ ]:
a=3
b=5

print('Son iguales?')
print('a=3')
print('b=5')
print(a==b)

Son iguales?
a=3
b=5
False

Si los dos número son diferentes

In [ ]:
print('Son diferentes?')
print(a!=b)

Son diferentes?
True

Si el primero es mayor que el segundo

In [ ]:
print('El primero es mayor que el segundo')
print(a>b)

El primero es mayor que el segundo
False

Si el segundo es mayor o igual que el primero

In [ ]:
print('El segundo es mayor o igual que el primero')
print(a<=b)

El segundo es mayor o igual que el primero
True

Realiza un programa que lea 2 números por teclado y determine los siguientes aspectos (es suficiene con mostrar True o False):

Si los dos números son iguales
Si los dos números son diferentes
Si el primero es mayor que el segundo
Si el segundo es mayor o igual que el primero

In [ ]:
n1 = float( input("Introduce el primer número: ") )
n2 = float( input("Introduce el segundo número: ") )

print("¿Son iguales? ", n1 == n2)
print("¿Son diferentes?", n1 != n2)
print("¿El primero es mayor que el segundo?", n1 > n2)
print("¿El segundo es mayor o igual que el primero?", n1 <= n2)

<p><a name="sltd"></a></p>

## 2.5.3 Strings, listas y diccionarios.

[[Secciones]](#sections)

<p><a name="strings"></a></p>

###2.5.1 Strings

Las variables que se usan para guardar un mensaje, palabra, etc, se conocen como `strings`

In [ ]:
s = "Hola mundo"
type(s)

str

In [ ]:
# Longitud del string: Número de caracteres en el string
len(s)

10

In [ ]:
# Reemplazo de un substring dentro de un string
s2 = s.replace("mundo","alumnos")
print(s2)

Hola alumnos

Podemos indexar los caracteres en un string mediante el uso de `[]`

In [ ]:
s[0],s[1],s[2],s[3]

('H', 'o', 'l', 'a')

In [ ]:
s[0:4]

'Hola'

Si omitimos en el intervalo el `start` o el `stop`, se toma por defecto el princio y el final de string, respectivamente

In [ ]:
s[:4]

'Hola'

In [ ]:
s[5:]

'mundo'

In [ ]:
s[:]

'Hola mundo'

También podemos definir el tamaño del paso usando la sintaxis `[inicio:final:paso]`(el valor por defecto del paso es 1, como se vio anteriormente)

In [ ]:
s[::1]

'Hola mundo'

In [ ]:
s[::2]

'Hl ud'

In [ ]:
s

'Hola mundo'

In [ ]:
s[::-1]

'odnum aloH'

A esta técnica se le conoce con el nombre se *slicing*.

**Ejemplos de formatos de strings**

In [ ]:
#Contatenación de strings con +
print("Común"+"mente")

Comúnmente

In [ ]:
'hola '*5

'hola hola hola hola hola '

In [ ]:
#La función print concatena dependiendo de como son las entradas.
#A continuación se muestran tres resultados diferentes 

print("Común" "mente")
print("Común","mente")
print(("Común","mente"))

Comúnmente
Común mente
('Común', 'mente')

In [ ]:
#Por otra parte, la función print convierte todos las entradas a strings
print("Común", 1.0, False)

Común 1.0 False

In [ ]:
# Podemos usar la función print en forma similar a como es usada en C

print("value = %f" %3.343569)

value = 3.343569

Python posee dos estilos de formatos. Un estilo más antiguo, en el que se especifica, por ejemplo, el número de cifras decimales que se imprimirá tendrá un número de tipo float denotado por %n.f y %.d, que transforma un número en un string, correspondiente a un numero decimal.

In [ ]:
s2 = "value1 = %.3f. value2 = %d" % (3.1415, 1.5)
print(s2)

value1 = 3.142. value2 = 1

El mismo string puede ser definido usando el nuevo estilo de formato

In [ ]:
s3 = 'value1 = {:.2f}, value2 = {}'.format(3.1415, 1.5)

print(s3)
type(s3)

value1 = 3.14, value2 = 1.5

str

In [ ]:
print("Las líneas nuevas son indicadas por \nlos espacios por \t.")

print(r"Las líneas nuevas son indicada por \n y los espacios por \t. r indica raw string")

Las líneas nuevas son indicadas por
los espacios por 	.
Las líneas nuevas son indicada por \n y los espacios por \t. r indica raw string

In [ ]:
s4="Nombre: {}\nNúmero: {}\nString: {}".format("Python", 2019, 4 * "-")
print(s4)

Nombre: Python
Número: 2019
String: ----

In [ ]:
strString = """String
con varias
líneas de texto."""
print(strString)

String
con varias
líneas de texto.

In [ ]:
print("Esto {verbo} una {sujeto}.".format(sujeto = "prueba", verbo = "es"))

Esto es una prueba.

F-Strings

In [ ]:
nombre='Camilo'
edad=30

In [ ]:
f'Hola mi nombre es {nombre} y tengo {edad} años'

'Hola mi nombre es Camilo y tengo 30 años'

In [ ]:
f'Hola mi nombre es {nombre} y tengo {365*edad} días'

'Hola mi nombre es Camilo y tengo 10950 días'

In [ ]:
f'Hola mi nombre es {nombre} y tengo {edad/100:.2f} siglos'

'Hola mi nombre es Camilo y tengo 0.30 siglos'

In [ ]:
s='Hola mundo'

<p><a name="alist"></a></p>

### 2.5.5. Listas

[[Secciones]](#sections)

Las listas son muy similares a los `strings` con la excepción de que los elementos de una lista pueden ser de cualquier tipo.

La sintaxis en Python es de la forma `[...]`.

In [ ]:
l=[0,1,2,3]
print(type(l))
print(l)

<class 'list'>
[0, 1, 2, 3]

Podemos usar las mismas técnicas de *slicing* que usamos en los *strings

In [ ]:
print(l[:])
print(l[0:2])
print(l[::2])

[0, 1, 2, 3]
[0, 1]
[0, 2]

In [ ]:
l[0]

0

Los elementos de una lista no tiene que ser todos del mismo

In [ ]:
l = [1, 'a', 1.0,[1,2,3]]
l

[1, 'a', 1.0, [1, 2, 3]]

Las listas en Python inhomogeneas y anidadas arbitrariamente:

In [ ]:
nested_list = [1, [2, [3, [4, [5]]]]]
nested_list

[1, [2, [3, [4, [5]]]]]

In [ ]:
l=[1,2,3]

In [ ]:
len(l)

3

Las listas desempeñan un papel muy importante en Python y, por ejemplo, se utilizan en bucles y otras estructuras de control de flujo (que se analizan a continuación). Hay una serie de funciones convenientes para generar listas de varios tipos, por ejemplo, la función de `range` (tenga en cuenta la función `range` de Python 3 crea un generador, por lo que tiene que usar la función de lista para obtener una lista):

In [ ]:
inicio = 1
final = 16
paso = 2

list(range(inicio, final, paso))

[1, 3, 5, 7, 9, 11, 13, 15]

In [ ]:
list(range(3,10,2))

[3, 5, 7, 9]

In [ ]:
# Convertir un string en una lista casteando mediante list

print(s)

s2 = list(s)

s2

Hola mundo

['H', 'o', 'l', 'a', ' ', 'm', 'u', 'n', 'd', 'o']

In [ ]:
s2[0]='K'
s2

['K', 'o', 'l', 'a', ' ', 'm', 'u', 'n', 'd', 'o']

In [ ]:
# Organización de la lista
s2.sort()

print(s2)

[' ', 'K', 'a', 'd', 'l', 'm', 'n', 'o', 'o', 'u']

In [ ]:
s3=sorted(s2)
print(s2,s3)

['H', 'o', 'l', 'a', ' ', 'm', 'u', 'n', 'd', 'o'] [' ', 'H', 'a', 'd', 'l', 'm', 'n', 'o', 'o', 'u']

In [ ]:
lista=[5,4,3,2,1]
sorted(lista)

[1, 2, 3, 4, 5]

***Adición, inserción, modificación y remoción de elementos de una lista***

In [ ]:
# Creación de una lista vacía
l = []

# Adición de elementos usando `append`
l.append("A")
l.append("d")
l.append("d")

print(l)

['A', 'd', 'd']

Podemos modificar una lista al asignar nuevos valores a elementos de esa lista, es decir, las listas son *mutables*.

In [ ]:
l[1] = "p"
l[2] = "t"

print(l)

['A', 'p', 't']

In [ ]:
l[1:3] = ["s", "m"]

print(l)

['A', 's', 'm']

Inserción de elementos mediante `insert`.

In [ ]:
l.insert(0, "i")
l.insert(1, "n")
l.insert(2, "s")
l.insert(3, "e")
l.insert(4, "r")
l.insert(5, "t")

print(l)

['i', 'n', 's', 'e', 'r', 't', 'A', 's', 'm']

Remoción del primer elemento de un valor específico mendiante `remove`

In [ ]:
l.remove("A")

print(l)

['i', 'n', 's', 'e', 'r', 't', 's', 'm']

In [ ]:
l.append('e')
l

['i', 'n', 's', 'e', 'r', 't', 's', 'm', 'e']

In [ ]:
l.remove('e')

In [ ]:
l

['i', 'n', 's', 'r', 't', 's', 'm', 'e']

Remoción de un elemento en una posición específica usando `del`

In [ ]:
del l[7]
del l[6]

print(l)

['i', 'n', 's', 'r', 't', 's']

In [ ]:
l.pop(0)

'i'

In [ ]:
l

['n', 's', 'r', 't', 's']

In [ ]:
quitar=l.pop(3)
l,quitar

(['n', 's', 'r', 's'], 't')

<p><a name="tuples"></a></p>

### 2.5.6. Tuplas

[[Secciones]](#sections)

Las tuplas son como las listas, excepto que estas no pueden ser modificadas una vez se han creado, es decir, son inmutables.

En Python, las tuplas son creadas usando la sintaxis (..., ..., ...), incluso ..., ...:

In [ ]:
point = (10, 20)

print(type(point))
print(point)

<class 'tuple'>
(10, 20)

Si intentamos asignar un nuevo valos a un elemento de la tupla, obtenemos un error:

In [ ]:
try:
    point[0] = 20
except(TypeError) as er:
    print("TypeError:", er)
else:
    raise

TypeError: 'tuple' object does not support item assignment

In [ ]:
point=3,3,3,3,3
point

(3, 3, 3, 3, 3)

In [ ]:
point=5,20,4
point

(5, 20, 4)

In [ ]:
point[0]

5

<p><a name="diccionarios"></a></p>

### 2.5.7. Diccionarios

[[Secciones]](#sections)

Los diccionarios son también parecidos a las listas, excepto que cada elemento es una pareja clave-valor. La sintaxis en los diccionarios es de la forma {key1 : value1, ...}:

In [ ]:
params = {"parameter1" : 1.0,
          "parameter2" : 2.0,
          "parameter3" : 3.0,}

print(type(params))
print(params)

<class 'dict'>
{'parameter1': 1.0, 'parameter2': 2.0, 'parameter3': 3.0}

In [ ]:
params['parameter1']

1.0

A las entradas de los diccionarios solo puede accerderse mediante el nombre de la clave.

In [ ]:
params["parameter2"]

2.0

In [ ]:
print("parameter1 = " + str(params["parameter1"]))
print("parameter2 = " + str(params["parameter2"]))
print("parameter3 = " + str(params["parameter3"]))

parameter1 = 1.0
parameter2 = 2.0
parameter3 = 3.0

In [ ]:
params["parameter1"] = "A"
params["parameter2"] = "B"

# add a new entry
params["parameter4"] = "D"

print("parameter1 = " + str(params["parameter1"]))
print("parameter2 = " + str(params["parameter2"]))
print("parameter3 = " + str(params["parameter3"]))
print("parameter4 = " + str(params["parameter4"]))

parameter1 = A
parameter2 = B
parameter3 = 3.0
parameter4 = D

In [ ]:
params.keys(),params.values()

(dict_keys(['parameter1', 'parameter2', 'parameter3', 'parameter4']),
 dict_values(['A', 'B', 3.0, 'D']))

In [ ]:
params.get('parameter4',0)

'D'

<p><a name="exercise0"></a></p>

### 2.5.8. Ejercicios y problemas

**EJERCICIO 1**

Escribir un programa que calcule el area de una triángulo donde se ingrese el valor de sus tres lados

Variables: a, b, c (Datos conocido)

s:         Área del triangulo (es el resultado esperado)

t:         Semiperimetro (Valor usado para la formula del area

$s = 	\sqrt{t(t-a)(t-b)(t-c)}$ formula del área del triángulo

siendo $t = \frac{(a+b+c)}{2}$

In [ ]:
# A continuación mostramos la forma de importa solamente la función deseada
# de la librería, con el fin de ahorrar recursos
from math import sqrt
a=float(input("Digite en lado a:  "))
b=float(input("Digite en lado b:  "))
c=float(input("Digite en lado c:  "))
# Calculamos la función t
t= (a+b+c)/2
s=sqrt(t*(t-a)*(t-b)*(t-c))
print("El área del triángulo es: ", s)

Digite en lado a:  4.5
Digite en lado b:  7
Digite en lado c:  6.2
El área del triángulo es:  13.738049124602805

**Ejercicio 2**

Dados el radio y altura de un cilindro calcule el area total y el volumen.

$Area Cilindro = 2\pi r(r+h)$

In [ ]:
from math import pi
r=float(input("Digite el valor del radio :  "))
h=float(input("Digite el valor de la altura :  "))
AC = 2*pi*r*(r+h)
print("El área del triángulo es: ", AC)

Digite el valor del radio :  1
Digite el valor de la altura :  9
El área del triángulo es:  62.83185307179586

**Ejercicio 3**

Dadas las tres dimensiones de un bloque rectangular (Prisma rectangular). calcule y muestre su área total y su volumen.

$Area = 2(ab+ ah+ bh)$

In [ ]:
a=float(input("Digite el valor del lado a :  "))
b=float(input("Digite el valor del lado b :  "))
h=float(input("Digite el valor del lado h :  "))
Area = 2*(a*b + a*h+ b*h)
print("El área del bloque rectangular es ", Area, "Unidades cuadradas")

Digite el valor del lado a :  1
Digite el valor del lado b :  1
Digite el valor del lado h :  1
El área del bloque rectangular es  6.0 Unidades cuadradas

**Ejercicio 4**

La siguiente fórmula proporciona el enésimo término **u** de una progresión aritmética

$u = a + (n - 1) r$

en donde **a** es el primer término, **n** es el la cantidad de términos y **r** es la razón entre dos
términos consecutivos. 

Calcular el valor de **r** dados u, a, n

Despejamos y obtenemos= $r= \frac{u}{a+(n-1)}$

In [ ]:
u=float(input("Digite el valor del termino enésimo:  "))
a=float(input("Digite el valor del primer término :  "))
n=float(input("Digite la cantidad de términos a ser cálculados:  "))
r= ((u)/(a+(n-1)))

print("La razón entre dos términos consecutivos ", r)

Digite el valor del termino enésimo:  1
Digite el valor del primer término :  1
Digite la cantidad de términos a ser cálculados:  1
La razón entre dos términos consecutivos  1.0

**Ejercicio 5**

El examen de una materia es el 70% de la nota total. Las lecciones constituyen el 20% y las tareas el 10% de la nota total. Ingrese como datos la nota del examen calificado sobre 100 puntos, la nota de una lección calificada sobre 10 puntos, y las notas de tres tareas calificadas cada una sobre 10 puntos. Calcule la calificación total sobre 100 puntos.

In [ ]:
NotaFinal=float(input("Digite el valor de la nota final:  "))
Leccion =float(input("Digite el valor de la leccion :  "))
NotaTarea1=float(input("Digite el valor de la tarea 1:  "))
NotaTarea2=float(input("Digite el valor de la tarea 2:  "))
NotaTarea3=float(input("Digite el valor de la tarea 3:  "))
CalifiacionTotal = ((NotaFinal*0.7)+(Leccion*0.2)+ (((NotaTarea1+NotaTarea2+NotaTarea3)/3)*0.1))

print("La calificacion Total del estudiante es:  ", CalifiacionTotal)

Digite el valor de la nota final:  9
Digite el valor de la leccion :  8
Digite el valor de la tarea 1:  1
Digite el valor de la tarea 2:  1
Digite el valor de la tarea 3:  1
La calificacion Total del estudiante es:   8.0

**Ejercicio 6**

Un modelo de crecimiento poblacional está dado por:  $n = 5t +2e^{0.1t}$, en donde n es el número de habitantes, t es tiempo en años. Se desea conocer el número de habitantes que habrían en los años 5, 10 y 20. Obtenga los resultados ejecutando tres veces el programa.

In [ ]:
from math import e
PoblacionActual =float(input("Digite la poblacion actual de su ciudad:  "))

n1= 5*5 + 2*e**(0.1*5)
n2= 5*10 + 2*e**(0.1*10)
n3= 5*20 + 2*e**(0.1*20)
print("La poblacion actual es:  ", PoblacionActual)
print("La poblacion dentro de 5 años será aproximadamente:  ", n1+PoblacionActual)
print("La poblacion dentro de 10 años será aproximadamente:  ", n2+PoblacionActual)
print("La poblacion dentro de 20 años será aproximadamente:  ", n3+PoblacionActual)

Digite la poblacion actual de su ciudad:  1000
La poblacion actual es:   1000.0
La poblacion dentro de 5 años será aproximadamente:   1028.2974425414002
La poblacion dentro de 10 años será aproximadamente:   1055.436563656918
La poblacion dentro de 20 años será aproximadamente:   1114.7781121978612

**Ejercicio 7**

Un ingeniero desea tener una cantidad de dólares acumulada en su cuenta de ahorros para su retiro luego de una cantidad de años de trabajo. Para este objetivo planea depositar un valor mensualmente. Suponga que el banco acumula el capital mensualmente mediante la siguiente fórmula:

$A= P\left [ \frac{(1+x)^{^{n}}-1}{x} \right ]$

**A:** Valor acumulado

**P:** Valor de cada depósito mensual

**n:** Cantidad de depósitos mensuales

**x:** Tasa de interés mensual

Calcule el valor acumulado ingresando como datos valores para **P**, **n**, **x**

In [ ]:
P=float(input("Digite el valor del deposito mensual:  "))
n=float(input("Digite la cantidad de desitos mensuales:  "))
x=float(input("Digite la cantidad de desitos mensuales:  "))
A = P*((1+x)**n)/(x)
print("El valor acumulado A:  ", A)

Digite el valor del deposito mensual:  100000
Digite la cantidad de dositos mensuales:  2
Digite la cantidad de dositos mensuales:  20000
El valor acumulado A:   2000200005.0

<p><a name="indent"></a></p>

## 2.6. Identación

[[Secciones]](#sections)

Los espacios en blanco son importantes en Python. De hecho, los espacios en blanco al comienzo de una línea son importantes. A esto se le conoce como *indentación*. Los espacios en blanco iniciales (espacios y tabuladores) al comienzo de la línea lógica se usan para determinar el nivel de indentación de la línea lógica, que a su vez se usa para determinar la agrupación de declaraciones.


Esto significa que las declaraciones que van juntas deben tener la misma indentación, por ejemplo:

In [ ]:
i = 5

print('El valor es ', i)
print('Repetimos, el valor es ', i)

El valor es  5
Repetimos, el valor es  5

Cada uno de estos conjuntos de declaraciones se llama un bloque. Veremos ejemplos de cómo los bloques son importantes más adelante. Una cosa que debes recordar es que la indentación incorrecta conlleva a `IndentationError`.

<p><a name="controlFlow"></a></p>

## 2.7. Control del flujo

[[Secciones]](#sections)

<p><a name="cond"></a></p>

### 2.7.1. Condicionales: if, elif, else
La sintaxis en Python para la ejecución de una condición  consiste en las palabras claves `if`, `elif` (else if), `else`:

In [ ]:
statement1 = False
statement2 = False

if statement1:
    print("statement1 es Verdadero")

elif statement2:
    print("statement2 es Verdadero")

else:
    print("statement1 y statement2 son Falsos")

statement1 y statement2 son Falsos

In [ ]:
if statement1:
  print('hola')

hola

También podemos tener sentencias if anidadas

In [ ]:
val = 100
if val < 200:
  print("El valor es menor a 200")
  if val == 150:
    print("es 150")
  elif val == 100:
    print("es 100")
  elif val == 50:
    print("es 50")
  elif val < 50:
    print("el valor es menor a 50")
else:
  print("El valor es mayor a 200")

El valor es menor a 200
es 100

<p><a name="exercise2"></a></p>

### 2.7.2. Ejercicios y problemas

* **Ejericio 1**

Dado un número entero, evalué, si resulta ser menor
que 100 mostrar un mensaje que diga “número pequeño”.

In [ ]:
#Decoración: Nombre del Algoritmo
print("-------------------------------------------------------")
print("EVALUAR SI NUMERO MENOR A 100.")
print("-------------------------------------------------------")
#Entradas
print("Ingrese un número: ")
x = int( input())
#Proceso
if x < 100:  
  print ("Número menor que 100")
elif x >100:
  print ("Número mayor  que 100")

-------------------------------------------------------
EVALUAR SI NUMERO MENOR A 100.
-------------------------------------------------------
Ingrese un número:
150
Número mayor  que 100

* **Ejercicio 2**

Ingresar 2 números enteros diferentes e imprimir el
menor de ellos con el mensaje “El menor es: --“.

In [ ]:
#Decoración: Nombre del Algoritmo
print("-------------------------------------------------------")
print("Ejemplo2: IMPRIMIR EL MENOR DE DOS NÚMEROS.")
print("-------------------------------------------------------")
#Entradas
print("Ingrese 2 números: ")
x = int( input("Primer Número: "))
y = int( input("Segundo Número: "))
print("\nSALIDA: ")
print("-------------------------------------------------------")

if x > y :
#Esto esta dentro del IF
  print("El menor es:", y)
else:
#Esto esta dentro del ELSE
  print("El menor es:", x)

-------------------------------------------------------
Ejemplo2: IMPRIMIR EL MENOR DE DOS NÚMEROS.
-------------------------------------------------------
Ingrese 2 números:
Primer Número: 5
Segundo Número: 7

SALIDA:
-------------------------------------------------------
El menor es: 5

* **Ejercicio 3**

Para el pago semanal a un obrero se consideran los siguientes datos: horas trabajadas, tarifa por hora y descuentos. Si la cantidad de horas trabajadas en la semana es mayor a 40, se le debe pagar las horas en exceso con una bonificación de 50% adicional al pago normal.

Instrumentación

**Variables**

**c:** Cantidad de horas trabajadas en la semana

**t:** Tarifa por hora

**d:** Descuentos que se aplican al pago semanal

**p:** Pago que recibe el obrero

In [ ]:
#Cálculo del pago semanal
c=float(input('Horas trabajadas: '))
t=float(input('Tarifa por hora: '))
d=float(input('Descuentos '))
if c<=40:
  p=c*t - d
else:
    p=40*t + 1.5*t*(c - 40) - d
print('Valor a pagar', p)

Horas trabajadas: 40
Tarifa por hora: 2500
Descuentos 1000
Valor a pagar 99000.0

* **Ejercicio 4**

Durante el semestre un estudiante debe realizar tres evaluaciones. Cada evaluación tiene una calificación y la nota total que recibe el estudiante es la suma de las dos mejores calificaciones.

Escribir un programa que lea las tres calificaciones y determine cual es la calificación total que recibirá el estudiante.

**Instrumentación**

**Variables**

**a, b, c:** Variables que recibirán los datos de las tres calificaciones

**t:** Variable con la suma de las dos mejores calificaciones

Solamente hay tres casos posibles y son excluyentes, por lo que se usarán dos decisiones anidadas para verificar dos casos y el tercero será la cláusula else.

In [ ]:
# Suma de calificaciones
a=int(input('Ingrese su primera calificación: '))
b=int(input('Ingrese su segunda calificación: '))
c=int(input('Ingrese su tercera calificación: '))
if a>=c and b>=c:
  t=a+b
else:
  if a>=b and c>=b:
    t=a+c
  else:
    t=b+c
print('Su calificación total es: ',t)

Ingrese su primera calificación: 5
Ingrese su segunda calificación: 4
Ingrese su tercera calificación: 1
Su calificación total es:  9

* **Ejercicio 5**

Dados el radio y altura de un cilindro, si la altura es mayor al radio calcule y muestre el valor del volumen del cilindro, caso contrario muestre el valor del área del cilindro.

In [ ]:
import math 
altura=int(input('Ingrese la altura del cilindro : '))
radio=int(input('Ingrese el radio del cilindro: '))
if altura < radio: 
  Volumen = math.pi*radio*(altura**2)
  print('El volumen del cilindo es : ',Volumen)
else:
    print('ERROR')

Ingrese la altura del cilindro : 2
Ingrese el radio del cilindro: 5
El volumen del cilindo es :  62.83185307179586

* **Ejercicio 6**

Dados el radio y altura de un cilindro, si la altura es mayor al radio calcule y muestre el valor del volumen, caso contrario muestre el mensaje: 'Error'

In [ ]:
import math 
altura=int(input('Ingrese la altura del cilindro : '))
radio=int(input('Ingrese el radio del cilindro: '))
if altura > radio: 
  Volumen = math.pi*radio*(altura**2)
  print('El volumen del cilindo es : ',Volumen)
else:
  ArealateralDeSuperficie = 2*math.pi*radio*altura
  print('El Area lateral de Superficie : ',ArealateralDeSuperficie)
  AreaTotalDeSuperficie = 2*math.pi*radio*altura+ 2*math.pi*radio**2
  print('El Area lateral de Superficie : ',AreaTotalDeSuperficie)

 * **Ejercicio 7**

 Dadas las dimensiones de un bloque rectangular, calcule las diagonales de las tres caras diferentes. Muestre el valor de la mayor diagonal.

![Ecuacion5.png]()

Como podemo observar, si tenemos los valores de B1, B2 y H podemos calulcar los valores de las diagonales ya que se forman triángulos rectángulos donde las diagonales son las hipotenusas de estos.

$CatetoA^{2}+CatetoB^{2}=Hipotenusa$


$Hipotenusa=\sqrt{CatetoA^{2}+CatetoB^{2}}$

In [ ]:
import math
Altura=int(input('Ingrese el valor altura del Bloque rectángular : '))
Base1=int(input('Ingrese el valor de la Bas1 1 Bloque rectángular: '))
Base2=int(input('Ingrese el valor de la Bas1 2 Bloque rectángular: '))
D1= math.sqrt(Base1**2 + Base2**2 )
print('El valor de la diagonal 1 en igual a : ',D1)
D2= math.sqrt(Base2**2 + Altura**2 )
print('El valor de la diagonal 2 en igual a : ',D2)
D3= math.sqrt(Base2**1 + Altura**2 )
print('El valor de la diagonal 3 en igual a : ',D3)

Ingrese el valor altura del Bloque rectángular : 5
Ingrese el valor de la Bas1 1 Bloque rectángular: 2
Ingrese el valor de la Bas1 2 Bloque rectángular: 2
El valor de la diagonal 1 en igual a :  2.8284271247461903
El valor de la diagonal 2 en igual a :  5.385164807134504
El valor de la diagonal 3 en igual a :  5.196152422706632


 * *Ejercicio 8*

Lea un número de dos cifras. Determinar si la suma de ambas cifras es un número par o impar. Muestre un mensaje

In [ ]:
Suma1 = int(input('Por favor digite el primer número a ser sumado : '))
Suma2 = int(input('Por favor digite el segundo número a ser sumado : '))
SumaTotal = Suma1 +  Suma2
if SumaTotal% 2== 0:
  print('El valor de la suma de los número digiatado es par : ',SumaTotal)
else:
  print('El valor de la suma de los número digiatado es impar : ',SumaTotal)

Por favor digite el primer número a ser sumado : 1
Por favor digite el segundo número a ser sumado : 2
El valor de la suma de los número digiatado es impar :  3

 * *Ejercicio 9*
 
Lea un número. Determine si es entero y múltiplo de 7

 * *Ejercicio 10*

Lea la cantidad de Kw que ha consumido una familia y el precio por Kw. Si la cantidad es mayor a 700, incremente el precio en 5% para el exceso de Kw sobre 700. Muestre el valor total a pagar.

 * *Ejercicio 11*

Lea un valor de temperatura t y un código p que puede ser 1 o 2. Si el código es 1 convierta la temperatura t de grados f a grados c con la fórmula c=5/9(t-32). Si el código es 2 convierta la temperatura t de grados c a f con la fórmula: f=32+9t/5, caso contrario muestre un mensaje de error.

 * *Ejercicio 12*

 Dadas las tres calificaciones de dos estudiantes. La calificación final de cada uno es la suma de sus dos mejores calificaciones. Muestre un mensaje que indique cual estudiante (1 o 2) tiene la mayor calificación final.

 * *Ejercicio 13*

 Dadas las tres calificaciones de un estudiante, encuentre y muestre la calificación mayor y la califiicación menor

 * *Ejercicio 14*
 
Dados los tres lados de un triángulo determine su tipo: Equilátero, Isòsceles, o Escaleno

 * *Ejercicio 15*

Dadas la abscisa y ordenada de dos puntos, calcule su distancia al origen y determine cual de los dos puntos (primero o segundo) está más cerca del origen. La respuesta deberá ser un mensaje: ‘Punto 1’ o ‘Punto 2’

![PlanoCartesiano.png]()



Fórmula de la distancia del punto (x, y) al origen:$ \sqrt{x^{2}+y^{2}}$

 * *Ejercicio 16*

 Un local vende sus productos con la siguiente promoción. Si compra hasta 5 artículos, no hay descuento. Si compra más de 5 artículos, pero menos de 10, el precio unitario se reduce en 5%. Si compra 10 o más artículos, el precio unitario se reduce en 8%. Ingrese un dato de cantidad y el valor del precio unitario original. Calcule y muestre el valor total a pagar.

 * *Ejercicio 17*

 Juan, Pedro y José trabajan en una empresa que paga semanalmente. Ingrese para cada uno los siguientes datos del trabajo semanal: horas trabajadas, salario por hora, y descuentos. Calcule el pago semanal que recibirá cada uno y determine cual de los tres recibirá el mayor pago semanal. No considere el pago de horas extras.

 * *Ejercicio 18*

 Lea las dimensiones de un bloque rectangular (largo, ancho y altura del bloque), y el diámetro de un agujero. Determine si es posible que el bloque pueda pasar por el agujero.
 Sugerencia: Calcule cada una de las tres diagonales del bloque. Si alguna de ellas tiene un valor menor al diámetro del agujero muestre el mensaje: **‘Si pasa por el agujero’.**

 * *Ejercicio 19*

 Un código de tres cifras debe cumplir la siguiente regla para que sea vàlido: La tercera cifra debe ser igual al mòdulo 10 del producto de las dos primeras cifras. Escriba un programa que lea un código y verifique si cumple la regla anterior. Muestre un mensaje correspondiente.
 
Ejemplo. 384 es un código vàlido pues el módulo de 3x8 en 10 es igual a 4

 * *Ejercicio 20*

El número de pulsaciones que debe tener una persona por cada 10 segundos de ejercicio aeróbico se calcula con la fórmula:

Género femenino (1): número de pulsaciones = (220 - edad en años)/10

Género masculino (2): número de pulsaciones = (210 - edad en años)/10

Lea la edad y el género y muestre el número de pulsaciones.

 * *Ejercicio 21*
 El índice de masa corporal IMC de una persona se calcula con la fórmula IMC=P/T2 en donde P es el peso en Kg. y T es la talla en metros.

Lea un valor de P y de T, calcule el IMC y muestre su estado según la siguiente tabla:

![Estado1.png]()

 * *Ejercicio 22*

 Otro reporte de salud muestra una tabla diferente del índice de masa corporal IMC de una persona que se calcula con la fórmula IMC=P/T2 en donde P es el peso en Kg. y T es la talla en metros.

Lea un valor de P y de T, calcule el IMC y muestre su estado según la siguiente tabla:

![Estado2.png]()

 * *Ejercicio 23*

 En un concurso hay tres jueces. La opinión del juez es 1 si está a favor y 0 si está en contra. Para que un participante pueda continuar en el concurso debe tener al menos dos votos favorables. Escriba un algoritmo que lea los votos de los tres jueces y muestre el resultado mediante un mensaje: CONTINUA o ELIMINADO. No sume votos. Debe compararlos.

 * *Ejercicio 24*

 Dadas las dimensiones de un bloque rectangular, calcule y muestre el área de la cara de mayor dimensión.

 * *Ejercicio 25*

 Se conocen tres de los cuatro números de una matriz cuadrada de tamaño 2. Lea estos tres números y determine cual debe ser el cuarto número para que el determinante de la matriz sea igual a 0.

 * *Ejercicio 26*

 Lea un número x y los números **a, b.** Suponga que **a<b.** y que **x ≠ a**, **x ≠ b**. Determine en que lugar se encuentra el número x, antes de **a**, entre **a** y **b** o después de b. Muestre un mensaje.

 * *Ejercicio 27*

 Lea las tres calificaciones que obtuvo un estudiante en una materia. No suponga que estos tres números están ordenados. Describa como ordenarlos en forma ascendente y muestre los números ordenados

 * *Ejercicio 28*

 Lea los números de matrícula de tres estudiantes que toman la materia A y los números de matrícula de tres estudiantes que toman la materia B. Encuentre cuantos estudiantes que toman la materia A, también toman la materia B.

 * *Ejercicio 29*

 Un almacén ofrece un producto con descuento según la siguiente tabla:

![Estado3.png]()


 Lea la cantidad comprada y determine cuanto debe pagar.

<p><a name="iter"></a></p>

## 2.8. Iteraciones y ciclos lógicos

En general, las instrucciones se ejecutan secuencialmente: la primera instrucción en una función se ejecuta primero, seguida de la segunda, y así sucesivamente. Puede haber una situación en la que necesite ejecutar un bloque de código varias veces.  Una instrucción de bucle nos permite ejecutar una instrucción o un grupo de instrucciones varias veces.

<p><a name="cicl"></a></p>

### 2.8.1. Ciclos for y while

El ciclo for ejecuta una secuencia de sentencias un número determinado de veces

In [ ]:
range(5)

range(0, 5)

In [ ]:
for i in range(5):
  print(i)

0
1
2
3
4

In [ ]:
suma=0
for i in range(5):
  suma+=i
  print('i=',i,'suma=',suma)

i= 0 suma= 0
i= 1 suma= 1
i= 2 suma= 3
i= 3 suma= 6
i= 4 suma= 10

También podemos iterar sobre listas

In [ ]:
vocales=["a","e","i", "o","u"]
for i in vocales:
  print(i)

a
e
i
o
u

In [ ]:
for i in range(len(vocales)):
  print (i,vocales[i])

0 a
1 e
2 i
3 o
4 u

In [ ]:
for i,vocal in enumerate(vocales):
  print(i,vocal)

0 a
1 e
2 i
3 o
4 u

El ciclo while repite una sentencia o grupo de sentencias mientras una condición dada es TRUE. Prueba la condición antes de ejecutar el cuerpo del ciclo.

In [ ]:
c = 4
while c > 0:
  print('c=',c,'se cumple la condición')
  c-=1

c= 4 se cumple la condición
c= 3 se cumple la condición
c= 2 se cumple la condición
c= 1 se cumple la condición

Podemos tener varias condiciones

In [ ]:
c = 10
while c > 0:
  if c > 1 and c!=5:
    print ("Voy a hacerlo "+str(c-1)+" veces más")
  elif c==5:
    print('Voy en '+str(c-1))
  else:
    print ("¡Este es el último!")
  c -= 1 #c=c-1

Voy a hacerlo 9 veces más
Voy a hacerlo 8 veces más
Voy a hacerlo 7 veces más
Voy a hacerlo 6 veces más
Voy a hacerlo 5 veces más
Voy en 4
Voy a hacerlo 3 veces más
Voy a hacerlo 2 veces más
Voy a hacerlo 1 veces más
¡Este es el último!

Podemos usar uno o más ciclos dentro de otro. Esto lo conocemos como ciclos anidados

In [ ]:
for i in range(2):
  for j in range(5):
    print("i: %d j: %d" %(i,j))

i: 0 j: 0
i: 0 j: 1
i: 0 j: 2
i: 0 j: 3
i: 0 j: 4
i: 1 j: 0
i: 1 j: 1
i: 1 j: 2
i: 1 j: 3
i: 1 j: 4

<p><a name="contr"></a></p>

### 2.8.2. Sentencias de control de ciclo: break y continue.

Las sentencias de control de ciclo cambian la ejecución de su secuencia normal. Cuando la ejecución deja un ámbito, todos los objetos automáticos que se crearon en ese ámbito se destruyen.

La sentencia de control *break* termina el ciclo actual y reanuda la ejecución en la siguiente instrucción.

In [ ]:
vocales

['a', 'e', 'i', 'o', 'u']

In [ ]:
for i in vocales:
  if i=="o":
    break
  print(i)

a
e
i

La sentencia de control *continue* rechaza todas las declaraciones restantes en la iteración actual del ciclo y mueve el control de nuevo a la parte superior de este

In [ ]:
for i in vocales:
  if i=="o":
    continue
  print(i)

a
e
i
u

<p><a name="exercise3"></a></p>

### 2.8.3. Ejercicios y problemas

 * *Ejercicio 1*

 Suma de los cuadrados de los primeros números naturales
Instrumentación

**Variables**
**n:** dato (número natural hasta el que se llegará)

**s:** suma de cuadrados

**i:** cada número natural

In [ ]:
#Suma de cuadrados
n=int(input('Ingrese el valor final: '))
s=0
i=1
while i<=n:
  c=i**2
  s=s+c
  i=i+1
print('La suma es: ', s)

Ingrese el valor final: 20
La suma es:  2870

 * *Ejercicio 2*

 En un cultivo se tiene una cantidad inicial de bacterias. Cada día esta cantidad se duplica. Determine en que día la cantidad excede a un valor máximo.

**Instrumentación**

**Variables**

**x:** Cantidad inicial de bacterias

**m:** Cantidad máxima de bacterias

**d:** Día

In [ ]:
#Crecimiento de la cantidad de bacterias
x=int(input('Ingrese la cantidad inicial '))
m=int(input('Ingrese la cantidad máxima '))
d=0;
while x<=m:
  x=2*x
  d=d+1
print('La cantidad excede al máximo en el dia: ', d)
print('La cantidad de bacterias al días contado: ', x)

Ingrese la cantidad inicial 200
Ingrese la cantidad máxima 5000
La cantidad excede al máximo en el dia:  5
La cantidad de bacterias al días contado:  6400

 * *Ejercicio 3*

 Dado un número entero, genere una secuencia numérica con la siguiente regla. Esta secuencia se denomina de Ulam. Esta secuencia siempre llega al número 1.


 ![Ecuacion1.png]()

 Una prueba manual de esta definición


 ![Tabla1.png]()


 **Instrumentación**

**Variable**

**x:** número entero positivo

In [ ]:
# Secuencia de Ulam
x=int(input('Ingrese el dato inicial: '))
while x>1:
  if x%2 == 0:
    x=x//2
  else:
    x=3*x+1
  print(x)

Ingrese el dato inicial: 20
10
5
16
8
4
2
1

 * *Ejercicio 4*

Describir un ciclo para mostrar cada entero entre 1 y 5 junto con su cuadrado

In [ ]:
for n in [1, 2, 3, 4, 5]:
  c=n**2
  print('Número:',n, 'El cuadrado' ,c)

Número: 1 El cuadrado 1
Número: 2 El cuadrado 4
Número: 3 El cuadrado 9
Número: 4 El cuadrado 16
Número: 5 El cuadrado 25

 * *Ejercicio 5*

Describir un ciclo que muestre cada nombre de las provincias de la costa ecuatoriana.

In [ ]:
for p in ['Guayas','Los Rios','El Oro', 'Manabí',
          'Sta. Elena','Esmeraldas']:
    print('Provincia: ',p)

Provincia:  Guayas
Provincia:  Los Rios
Provincia:  El Oro
Provincia:  Manabí
Provincia:  Sta. Elena
Provincia:  Esmeraldas

 * *Ejercicio 6*

Describir un ciclo para mostrar cada entero entre 1 y 5 junto con su cuadrado:

In [ ]:
for n in range(1,6):
  c=n**2
  print('Número: ',n,' Cuadrado: ',c)

Número:  1  Cuadrado:  1
Número:  2  Cuadrado:  4
Número:  3  Cuadrado:  9
Número:  4  Cuadrado:  16
Número:  5  Cuadrado:  25

 * *Ejercicio 7*

Se necesita sumar los cuadrados de los primeros n números naturales.

**Instrumentación**

**Variables n:** número final

**i:** cada número natural

**s:** suma de los cuadrados

In [ ]:
#Suma de cuadrados
n=int(input('Ingrese el valor final: '))
s=0
for i in range(1,n+1):
  c=i**2
  s=s+c
  print('La suma es: ',s)

Ingrese el valor final: 5
La suma es:  1
La suma es:  5
La suma es:  14
La suma es:  30
La suma es:  55

 * *Ejercicio 7*

 Calcule y muestre el promedio de un grupo de datos ingresados desde el teclado

**Instrumentación**
**Variables n:** cantidad de datos

**i:** conteo de ciclos

**x:** cada dato ingresado desde el teclado s: suma de los datos

**p:** promedio

In [ ]:
#Promedio de un grupo de datos
n=int(input('Cantidad de datos: '))
s=0
for i in range(n):
  x=float(input('Ingrese el siguiente dato: '))
  s=s+x
p=s/n
3
print('El promedio es: ',p)

Cantidad de datos: 1
Ingrese el siguiente dato: 2
El promedio es:  2.0


 * *Ejercicio 8*

Dado un entero positivo n, se desea verificar que la suma de los primeros n números impares es igual a n2

Ejemplo. n = 5: 1 + 3 + 5 + 7 + 9 = 52

**Instrumentación**

**Variables**

**n:** Cantidad de números impares

**imp:** Cada número impar

**s:** Suma de impares

**i:** Conteo de ciclos

In [ ]:
# Suma de impares
n=int(input('Ingrese la cantidad de impares: '))
s=0
imp=1
for i in range(n):
  s=s+imp
  imp=imp+2
if s==n**2:
  print('Verdadero')
else:
  print('Falso')

Ingrese la cantidad de impares: 12
Verdadero


 * *Ejercicio 9*


Lea un grupo de datos (precios) desde el teclado. Encuentre y muestre el mayor valor

**Instrumentación**

**Variables n:** cantidad de datos

**i:** conteo de ciclos

**x:** cada dato ingresado desde el teclado

**t:** el mayor valor

La variable **t** que contendrá el mayor valor se la inicia con cero. En un ciclo se ingresará cada dato y se lo comparará con **t**, si es mayor, la variable t será asignada con el valor del dato ingresado. Al finalizar el ciclo, **t** contendra el mayor valor

In [ ]:
#El mayor valor de un grupo de datos
n=int(input('Cantidad de datos: '))
t=0
for i in range(n):
  x=float(input('Ingrese el siguiente dato: '))
  if x>t:
    t=x
print('El mayor valor es: ',t)

Cantidad de datos: 5
Ingrese el siguiente dato: 45
Ingrese el siguiente dato: 37
Ingrese el siguiente dato: 28
Ingrese el siguiente dato: 56
Ingrese el siguiente dato: 24
El mayor valor es:  56.0

* *Ejercicio 9*

Dado un número entero positivo, encuentre todos sus divisores enteros positivos.

**Instrumentación**

**Variables n:** número entero positivo (dato)

**d:** cada número entero entre 1 y n, posible divisor de n

In [ ]:
#Divisores de un entero
n=int(input('Ingrese un entero positivo: '))
for d in range (1,n+1):
  if n%d==0:
    print('Divisor: ',d)

Ingrese un entero positivo: 21
Divisor:  1
Divisor:  3
Divisor:  7
Divisor:  21

* *Ejercicio 9*

Dado un número entero, cuente sus divisores enteros exactos.

**Instrumentación**

**Variables n:** número entero positivo (dato)

**x:** cada número entero entre 1 y n, posible divisor de n

**c:** cantidad de divisores

In [ ]:
#Divisores de un entero
n=int(input('Ingrese un entero positivo: '))
c=0
for d in range (1,n+1):
  if n%d==0:
    c=c+1
print('Cantidad de divisores: ',c)

Ingrese un entero positivo: 20
Cantidad de divisores:  6

<p><a name="func"></a></p>

## 2.9. Funciones y clases

DRY: Don't Repeat Yourself

<p><a name="funci"></a></p>

---



---



### 2.9.1. Funciones

Una función es un bloque de código organizado y reutilizable que se utiliza para realizar una única acción relacionada. Las funciones proporcionan una mejor modularidad para su aplicación y un alto grado de reutilización de código.

>`def Nombre(arg1,arg2,...):`
>> `sentencias`

Definamos la función exponencial $a^b$

In [ ]:
def Exp(a,b):
  exponencial = a**b
  print(exponencial)
  return
  
Exp(2,3)

8

La sentencia *return* termina la función,  devolviendo opcionalmente uno o varios valores. Una declaración de retorno sin argumentos es lo mismo que devolver *none* (como en el caso anterior)

In [ ]:
def doble(a):
  print(a)
  print(2*a)
  return 2*a

In [ ]:
variable=doble(3)

3
6

In [ ]:
print(variable)

6

In [ ]:
def Exp(a,b):
  return a**b

In [ ]:
def Exp2(a,b):
  return a**b,a**b+1,a**b+2

In [ ]:
variable=Exp(2,3)
variable

8

In [ ]:
print(Exp(2,3),type(Exp(2,3)))

8 <class 'int'>

In [ ]:
print(Exp2(2,2),type(Exp2(2,2)))

(4, 5, 6) <class 'tuple'>

In [ ]:
def multiplicar(a,b=2):
  return a*b

In [ ]:
multiplicar(3,4)

12

In [ ]:
multiplicar(3)

6

In [ ]:
def valor_maximo(lista):
  return max(lista)

valor_maximo([0,1,1,43,23,132,999,9])

999

In [ ]:
def valor_max(lista):
  return sorted(lista)[-1]

In [ ]:
def valor_max(lista):
    maximo=lista[0]
    for i in lista:
        if i > maximo:
            maximo=i
    return maximo

In [ ]:
valor_max([])

In [ ]:
l = [1, 6, 7, 8, 9, 0, 14, 35 , 18]
max = l[0]
for i in l: 
    if i > max: 
        max = i 
print(max)

35

<p><a name="class"></a></p>

### 2.9.2 Clases

Las clases proporcionan un medio de agrupar datos y "funcionalidad". La creación de una nueva clase crea un nuevo tipo de objeto, lo que permite crear nuevas *instancias* de ese tipo. Cada instancia de la clase puede tener sus propios atributos. Las instancias de una clase también pueden tener *métodos* (definidos por su clase) para modificar su estado.

>class Name():
>>sentencias

Los atributos son como propiedades que queremos añadir a la clase

In [ ]:
class Auto():
  marca = ''
  color = ''

Creemos un objeto de la clase Auto con algunos atributos

In [ ]:
mi_auto = Auto()
mi_auto.marca = 'ferrari'
mi_auto.color = 'rojo'

print(mi_auto.marca)
print(mi_auto.color)

ferrari
rojo

In [ ]:
mi_auto2 = Auto()
mi_auto2.marca = 'nissan'
mi_auto2.color = 'blanco'

print(mi_auto2.marca)
print(mi_auto2.color)

nissan
blanco

Dentro de las clases podemos definir funciones, conocidas como *métodos*

In [ ]:
class Persona():
  nombre = ''
  edad = ''
  
  def decir_nombre(self):
    print('Hola, mi nombre es',self.nombre)
    
  def decir_edad(self):
    print(f'Tengo {self.edad} años')

In [ ]:
carolina = Persona()
carolina.nombre = 'carolina'
carolina.edad = 20

In [ ]:
carolina.decir_nombre()

Hola, mi nombre es carolina

In [ ]:
carolina.decir_edad()

Tengo 20 años

In [ ]:
persona2 = Persona()
persona2.nombre = 'Camilo'
persona2.edad = 30

In [ ]:
persona2.decir_nombre()
persona2.decir_edad()

Hola, mi nombre es Camilo
Tengo 30 años

Los métodos necesitan tener un argumento convenientemente llamado self, que se refiere al objeto del método que está siendo llamado. Podemos pasar más de un argumento si así lo deseamos

In [ ]:
class Persona:
    nombre = ''
    edad = ''
     
    def print_informacion(self, nombre, edad):
        print('nombre:',self.nombre)
        print('edad:',self.edad)
             
carlos = Persona()
carlos.nombre = 'carlos'
carlos.edad = '30'
carlos.print_informacion(carlos.nombre, carlos.edad)

nombre: carlos
edad: 30

La operación de creación de instancias crea un objeto vacío. A muchas clases les gusta crear objetos con instancias personalizadas a un estado inicial específico. Por lo tanto, una clase puede definir un método especial llamado __init __ (), como este:

In [ ]:
class Person:
  def __init__(self,n,e):
    print('Corriendo init')
    self.nombre = n
    self.edad = e

In [ ]:
mario = Person('mario','55')

Corriendo init

In [ ]:
print('nombre:',mario.nombre)
print('edad:',mario.edad)

nombre: mario
edad: 55

clase para un punto cartesiano (x,y) desplazar (dx,dy)

In [ ]:
class punto():
  def __init__(self,x,y):
    self.x=x
    self.y=y
  def desplazar(self,dx,dy):
    self.x+=dx
    self.y+=dy
  def __str__(self):
    return f'x: {self.x}, y: {self.y}'

In [ ]:
punto1=punto(0,0)
print(punto1)
punto1.desplazar(1,1)
print(punto1)
punto1.desplazar(1,1)
print(punto1)

x: 0, y: 0
x: 1, y: 1
x: 2, y: 2

In [ ]:
class circulo(punto):
  def __init__(self,x,y,r):
    self.x=x
    self.y=y
    self.r=r
  def __str__(self):
    return f'x: {self.x}, y: {self.y}, r: {self.r}'

In [ ]:
mi_circulo=circulo(0,0,1)
mi_circulo.desplazar(1,1)
mi_circulo.desplazar(1,1)
print(mi_circulo)

x: 2, y: 2, r: 1

<p><a name="exercise4"></a></p>

### 2.9.3. Ejercicios y problemas